### ISSUE TITLE
디자인 프로토타입

### ISSUE THREAD

**Issue by ssubinsong** [Queist/swpp-project#38]
- [Interactive View](https://design.penpot.app/#/view/5f00eb50-2506-11ec-985f-f08c5eccf3df?page-id=5f00eb51-2506-11ec-985f-f08c5eccf3df&index=0&share-id=64b8d440-264b-11ec-bdd0-f35c6ae458e9)
- [PDF](https://www.dropbox.com/s/5d2nfra2avtqajr/ReJourN%20design%20prototype.pdf?dl=0)

PDF로는 개별 페이지는 볼 수 있는데 페이지 간의 관계를 볼 수 없어서... 직접 클릭해가면서 화면 바뀌는거 보려면 Interactive View로 보기!
(피드백할 거 있으면 Interactive View나 PDF 들어가서 원하는 지점 찍어서 코멘트 달아줘도 됨)

**Comment by ddony8128** [comment]
기획을 더 명확히 해야 디자인에도 피드백할 수 있을 것 같다는 생각이 드네..
 친구 목록이나 레포지토리 소유한 그룹을 확인할 수 있는 창이 들어갈 위치나 다른 사람의 개인 페이지에 들어갔을 때 친구 추가 등을 할 수 있는 차이점 등이 디자인 시안에도 반영되어야 하는데 이 부분이 아직 기획 상 명확하지 않으니까....
 근데 메인 로고는 직접 만든거야?? 앞으로 더 예쁜 걸로 바꿀 수도 있겠지만 지금 로고랑 전체적인 색 느낌 좋은 것 같아.
 다른 페이지들은 화면을 꽉꽉 채워서 활용하는데 그에 비해 게시글 / 레포 / 디스커션 작성 창은 공간이 비어보여. 위쪽에 지금 사용자가 뭘 하고 있는지 명시해주는 페이지 제목이 들어가고 입력 창도 양옆으로 늘려서 공간을 충분히 활용할 수 있게 해주면 좋을 것 같아. 나중에 그 자리에 뭔가 다른 게 들어갈 수도 있겠지만..?

**Comment by ssubinsong** [comment]
> 기획을 더 명확히 해야 디자인에도 피드백할 수 있을 것 같다는 생각이 드네.. 친구 목록이나 레포지토리 소유한 그룹을 확인할 수 있는 창이 들어갈 위치나 다른 사람의 개인 페이지에 들어갔을 때 친구 추가 등을 할 수 있는 차이점 등이 디자인 시안에도 반영되어야 하는데 이 부분이 아직 기획 상 명확하지 않으니까.... 근데 메인 로고는 직접 만든거야?? 앞으로 더 예쁜 걸로 바꿀 수도 있겠지만 지금 로고랑 전체적인 색 느낌 좋은 것 같아. 다른 페이지들은 화면을 꽉꽉 채워서 활용하는데 그에 비해 게시글 / 레포 / 디스커션 작성 창은 공간이 비어보여. 위쪽에 지금 사용자가 뭘 하고 있는지 명시해주는 페이지 제목이 들어가고 입력 창도 양옆으로 늘려서 공간을 충분히 활용할 수 있게 해주면 좋을 것 같아. 나중에 그 자리에 뭔가 다른 게 들어갈 수도 있겠지만..?

로고는 그냥 영문 폰트 중에 괜찮은거 골라서 비행기 그림이랑 합친거야 ㅎㅎ 폰트 하나하나 적용해보느라 힘들엇다,,,

그리고 게시글 작성화면 비어보인다는건 나도 공감해. 그냥 유나가 짜준 그림에 저렇게 되어있어서 저렇게 했는데 그냥 다른 페이지들처럼 왼쪽에 사이드바는 유지하고 오른쪽 영역에 게시글 작성화면 넣는게 나을거같음. 입력 창은 너무 많이 늘리면 가독성이 떨어져서 글쓸때 더 불편할거야. 지금이 좋은거같아 나는..!

**Comment by Queist** [comment]
"프로필과 컨텐츠 (포스트나 레포)를 구분하는 선" 과 "프로필" 사이의 간격이 조금 좁은 것 같음.
Explore tab 눌렀을 때 하위 탭들 배치가 조금 부자연스러운 느낌? 근데 이 부분은 나머지 디자인이 끝나야 확실히 말할 수 있을듯.
